name: Selenium CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "prashant_qa" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests
        run: mvn -B test -f EcommerceDemo/pom.xml -Dbrowser=chrome -Dheadless=true
        continue-on-error: true

      - name: Upload Extent Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: EcommerceDemo/target/extent-reports/
          retention-days: 30

      - name: Upload Surefire Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: EcommerceDemo/target/surefire-reports/
          retention-days: 30

      - name: Publish TestNG results (Surefire XML)
        if: ${{ always() }}
        uses: dorny/test-reporter@v2
        with:
          name: Test Results
          path: EcommerceDemo/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: "false"

      - name: Build with Maven
        run: mvn -B package -f EcommerceDemo/pom.xml -DskipTests
