name: Selenium CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "prashant_qa" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@
      
      - name: Run Tests
        run: mvn -B test -f EcommerceDemo/pom.xml -Dbrowser=chrome -Dheadless=true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file EcommerceDemo/pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
